# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/archjules/Documents/Emulation/Gameboy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/archjules/Documents/Emulation/Gameboy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/archjules/Documents/Emulation/Gameboy/CMakeFiles /home/archjules/Documents/Emulation/Gameboy/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/archjules/Documents/Emulation/Gameboy/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gameboy

# Build rule for target.
gameboy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gameboy
.PHONY : gameboy

# fast build rule for target.
gameboy/fast:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/build
.PHONY : gameboy/fast

src/cb.o: src/cb.c.o

.PHONY : src/cb.o

# target to build an object file
src/cb.c.o:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/cb.c.o
.PHONY : src/cb.c.o

src/cb.i: src/cb.c.i

.PHONY : src/cb.i

# target to preprocess a source file
src/cb.c.i:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/cb.c.i
.PHONY : src/cb.c.i

src/cb.s: src/cb.c.s

.PHONY : src/cb.s

# target to generate assembly for a file
src/cb.c.s:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/cb.c.s
.PHONY : src/cb.c.s

src/cpu.o: src/cpu.c.o

.PHONY : src/cpu.o

# target to build an object file
src/cpu.c.o:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/cpu.c.o
.PHONY : src/cpu.c.o

src/cpu.i: src/cpu.c.i

.PHONY : src/cpu.i

# target to preprocess a source file
src/cpu.c.i:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/cpu.c.i
.PHONY : src/cpu.c.i

src/cpu.s: src/cpu.c.s

.PHONY : src/cpu.s

# target to generate assembly for a file
src/cpu.c.s:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/cpu.c.s
.PHONY : src/cpu.c.s

src/instruction.o: src/instruction.c.o

.PHONY : src/instruction.o

# target to build an object file
src/instruction.c.o:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/instruction.c.o
.PHONY : src/instruction.c.o

src/instruction.i: src/instruction.c.i

.PHONY : src/instruction.i

# target to preprocess a source file
src/instruction.c.i:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/instruction.c.i
.PHONY : src/instruction.c.i

src/instruction.s: src/instruction.c.s

.PHONY : src/instruction.s

# target to generate assembly for a file
src/instruction.c.s:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/instruction.c.s
.PHONY : src/instruction.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/main.c.s
.PHONY : src/main.c.s

src/memory.o: src/memory.c.o

.PHONY : src/memory.o

# target to build an object file
src/memory.c.o:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/memory.c.o
.PHONY : src/memory.c.o

src/memory.i: src/memory.c.i

.PHONY : src/memory.i

# target to preprocess a source file
src/memory.c.i:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/memory.c.i
.PHONY : src/memory.c.i

src/memory.s: src/memory.c.s

.PHONY : src/memory.s

# target to generate assembly for a file
src/memory.c.s:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/memory.c.s
.PHONY : src/memory.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gameboy"
	@echo "... src/cb.o"
	@echo "... src/cb.i"
	@echo "... src/cb.s"
	@echo "... src/cpu.o"
	@echo "... src/cpu.i"
	@echo "... src/cpu.s"
	@echo "... src/instruction.o"
	@echo "... src/instruction.i"
	@echo "... src/instruction.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/memory.o"
	@echo "... src/memory.i"
	@echo "... src/memory.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

